# Generated by Django 6.0.7 on 2026-07-21 01:27

import chatbot.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chatbot", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="coursedocument",
            name="file",
            field=models.FileField(
                blank=True, null=True, upload_to=chatbot.models.document_upload_path
            ),
        ),
        migrations.AddField(
            model_name="coursedocument",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="uploaded_documents",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="coursedocument",
            name="raw_text",
            field=models.TextField(blank=True),
        ),
    ]
