# Generated by Django 6.0.7 on 2026-08-31 12:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("learning", "0005_question_explanation"),
        ("mastery", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ReviewSchedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ease_factor", models.FloatField(default=2.5)),
                ("interval_days", models.PositiveIntegerField(default=1)),
                ("repetitions", models.PositiveIntegerField(default=0)),
                ("next_review_at", models.DateTimeField(db_index=True)),
                ("last_reviewed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="review_schedules",
                        to="learning.question",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="review_schedules",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["next_review_at"],
                "unique_together": {("student", "question")},
            },
        ),
    ]
