# Generated by Django 6.0.7 on 2026-07-21 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("learning", "0002_topic_owner_alter_topic_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="source",
            field=models.CharField(
                choices=[("admin", "Admin-authored"), ("generated", "LLM-generated")],
                default="admin",
                max_length=10,
            ),
        ),
    ]
