# Generated by Django 6.0.7 on 2026-08-16 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("learning", "0004_course_topic_course"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="explanation",
            field=models.TextField(blank=True, default=""),
        ),
    ]
